server:
  port: 6001
spring:
  application:
    name: micro-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

info:
  author.name: wubiao
  app.name: microservice
  server.port: ${server.port}
  application.name: ${spring.application.name}
zuul:
  routes:
    order:
      serviceid
